name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps

      - name: Run Playwright tests
        run: |
          pnpm playwright test --config ./playwright.arrange.config.ts || true
          pnpm playwright test
        env:
          PLAYWRIGHT_WATCH_ORGANIZATION: ${{ vars.PLAYWRIGHT_WATCH_ORGANIZATION }}
          PLAYWRIGHT_WATCH_PROJECT: ${{ vars.PLAYWRIGHT_WATCH_PROJECT }}
          PLAYWRIGHT_WATCH_API_KEY: ${{ secrets.PLAYWRIGHT_WATCH_API_KEY }}
          PLAYWRIGHT_WATCH_SUPABASE_PROJECT: ${{ secrets.PLAYWRIGHT_WATCH_SUPABASE_PROJECT }}
          PLAYWRIGHT_WATCH_SUPABASE_PUBLIC_KEY: ${{ secrets.PLAYWRIGHT_WATCH_SUPABASE_PUBLIC_KEY }}
          PLAYWRIGHT_WATCH_E2E_TEST_RUN: true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
