name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    name: Release & Publish

    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        name: Release please
        with:
          release-type: node
          package-name: release-please-action

      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Install Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
          scope: '@playwright-watch'

      - uses: pnpm/action-setup@v2
        if: ${{ steps.release.outputs.release_created }}
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        if: ${{ steps.release.outputs.release_created }}
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        if: ${{ steps.release.outputs.release_created }}
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm install

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm build

      - name: Test
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm test

      - name: Publish to GitHub
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm publish dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npmjs.org
        working-directory: ./dist
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm publish --@playwright-watch:registry=https://registry.npmjs.org
